#!/usr/bin/env bash
# function shell with dig
dig_input(){
# if second argument donest exist, search for all records
if [[ $# -eq 1 ]]; then
	# subdomains hard codded
	subdomains=("www" "lb-01" "web-01" "web-02")
	for word in "${subdomains[@]}"; do
		sub_dom="$word.$1"
		result=$(dig +noall +answer "$sub_dom" | awk '{if ($5) print $5}')
		echo "The subdomain $word is a A record and points to $result"
	done
# search for specific sub domain
else
	# subdomain holds forex www.domain.com
	subdomain="$2.$1"
	result=$(dig +noall +answer "$subdomain"| awk '{if ($5) print $5}')
	echo "The subdomain $2 is a A record and points to $result"
fi;
}
dig_input "$@"
