#!/usr/bin/env bash
# function shell with dig
dig_input(){
# if second argument donest exist, search for all records
if [[ $# -eq 1 ]]; then
	# num of lines that hold records
	while IFS= read -r line; do
		# echo "$line"
		result=$(echo "$line" | awk '{if ($5) print $5}')
		sub_dom=$(echo "$line" | awk '{if ($1) print $1}')
		echo "The subdomain $sub_dom is a A record and points to $result"
	done <<< "$(dig +noall +answer "$1")"
# search for specific sub domain
else
	result=$(dig +noall +answer "$2"| awk '{if ($5) print $5}')
	echo "The subdomain $2 is a A record and points to $result"
fi;
}
dig_input "$@"
