#!/usr/bin/env bash
# transfe file using scp
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    path="$1"
	ip="$2"
	user="$3"
	key="$4"
    scp -i "$key" -o StrictHostKeyChecking=no "$path" "$user@$ip:~/"
fi
