#!/usr/bin/env bash
# applying redirect

sudo apt-get update
sudo apt-get install -y nginx


#replacing data in default file in sities_available
replace_string="server {\nlisten 80 default_server;\nroot /var/www/html;\nindex index.html index.htm index.nginx-debian.html;\nserver_name _;\nlocation /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}}"


#using sed
echo "$replace_string" | sudo tee /etc/nginx/sites-available/default

#refreshing server
sudo service nginx restart
