#!/usr/bin/env bash
# applying redirect

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir /redirect_me
printf %s "server {
listen 80 default_server;
location /redirect_me {
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
}" > /etc/nginx/sites_available/default

sudo service nginx restart