#!/usr/bin/env bash
# applying redirect
# first make a new path in the server root

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html

#replacing data in default file in sities_available
printf %s "server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html index.htm;

location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

server_name _;
error_page 404 /error.html;
location /404 {
root /var/www/html;
}" > /etc/nginx/sites-available/default

#refreshing server
sudo service nginx restart
