#!/usr/bin/env bash
# applying redirect

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > error.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files / =404;
        }
        # applyin redirect
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 /error.html;

}
" | sudo tee /etc/nginx/sites-available/default

#refreshing server
sudo service nginx restart
