#!/usr/bin/env bash
# custom http request header

#!/usr/bin/env bash
# Update package lists to get the lates update when installing
sudo apt-get update

# Install Nginx, -y to make a default yes for all questions
sudo apt-get install -y nginx

# Create a simple "Hello World!" page
# tee do both show output to the terminal, write on file
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files / =404;
                add_header X-Served-By $(hostname);
        }
        # applyin redirect
        location /redirect_me {
                return 301;
        }
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
