#!/usr/bin/env bash
# install load balancer
# refresh the package list
sudo apt-get update

# install the haproxy
sudo apt install haproxy
# to check init script
sudo service haproxy status
# copy tha main file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# configure it to the servers
echo "
frontend myfrontend
  mode http
  bind *:80
  default_backend web_servers
backend web_servers
  mode http
  balance roundrobin
  server 486992-web-01  18.207.1.174:80 check
  server 486992-web-02 54.226.26.233:80 check"
  | sudo tee /etc/haproxy/haproxy.cfg

# restart
sudo service haproxy restart
