#!/usr/bin/env bash
# install load balancer
# refresh the package list
sudo apt-get -y update

# install the haproxy
sudo apt-get install -y haproxy
# to check init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# copy tha main file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
# configure it to the servers
echo "
frontend myfrontend
  bind *:80
  mode http
  default_backend web_servers

backend web_servers
  balance roundrobin
  server 486992-web-01  18.207.1.174:80 check
  server 486992-web-02 54.226.26.233:80 check
"
  | sudo tee /etc/haproxy/haproxy.cfg

# restart
sudo service haproxy restart
