#!/usr/bin/env bash
# create a backup file for mysql dbs
# The MySQL dump must contain all your MySQL databases
# The MySQL dump must be named backup.sql
# MySQL dump file has to be compressed to a tar.gz archive
#This archive must have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database must be root
# The Bash script accepts one argument that is the password used to connect to the MySQL database
current_date=$(date +%d-%m-%Y)
mysql -u root -p "$1"
mysqldumb --all-databases > backup.sql
tar -czf  ${current_date}.tar.gz backup.sql
# outpt 1-08-2024.tar.gz
