#!/usr/bin/env bash
# Update package lists to get the lates update when installing
sudo apt-get update

# Install Nginx, -y to make a default yes for all questions
sudo apt-get install -y nginx

# Ensure Nginx is listening on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart