#!/usr/bin/env bash
# bash scrip to imitate init
if [ "$1" = "start" ]; then
	./manage_my_process &
	echo "manage_my_process started"
	echo $! > /var/run/my_process.pid
elif [ "$1" = "stop" ]; then
	if [ -f /var/run/my_process.pid ]; then
		kill -SIGINT "$(cat /var/run/my_process.pid)"
		rm /var/run/my_process.pid
	fi
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
	if [ -f /var/run/my_process.pid ]; then
		rm /var/run/my_process.pid
	fi
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
