#!/usr/bin/env bash
# bash scrip to imitate init
if [ "$1" = "start" ]
	./manage_my_process &
	echo "manage_my_process started"
	echo $! > /var/run/my_process.pid
elsif [ "$1" = "stop" ]
	kill -SIGINT $(cat my_process.pid)
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elsif [ "$1" = "restart" ]
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
