#!/usr/bin/env bash
# command to allow ports => http 80, https 443, ssh 22
sudo ufw default deny incoming
sudo ufw default allow incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
