#!/usr/bin/env bash

sudo -u nginx sed -i 's/listen 8080 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple "Hello World!" page
# tee do both show output to the terminal, write on file


# Restart Nginx without using systemctl
sudo -u nginx service nginx restart
