#!/usr/bin/env bash
# configure it to our needs so that you can connect to a server without typing a password.
# this applies to all servers
Host *
IdentityFile ~/.ssh/school
PasswordAuthentication no
